name: Build and publish

on: push
jobs:
  dockerize:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.0
        with:
          timeZone: 1
          format: 'YYYY-MM-DD-HH-mm-ss'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build_main
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: |
            xscanner/docs:${{ steps.time.outputs.time }}
            xscanner/docs:latest

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install prerequisite Python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install prerequisite Latex packages
        run: sudo apt-get update -y && sudo apt-get install -y latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

      - name: Build HTML docs
        run: sphinx-build -M html docs build

      - name: Build Latex and PDF docs
        run: sphinx-build -M latexpdf docs build

      - name: Upload HTML documentation artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: docs-html
          path: build/html

      - name: Upload PDF documentation artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v2
        with:
          name: docs-pdf
          path: build/latex/iac-scanner-documentation.pdf

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download HTML docs artifact
        uses: actions/download-artifact@v2
        with:
          name: docs-html
          path: build/html

      - name: Deploy docs to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
